services:
  - type: web
    name: psx-score-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api:app --bind 0.0.0.0:$PORT --timeout 180 --workers 2 --threads 4
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
